const typographyVariants = {
  titleMD: {
    fontSize: '90px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'uppercase',
    lineHeight: '108px',
  },
  titleXS: {
    fontSize: '64px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'uppercase',
    lineHeight: '77px',
  },
  subTitle: {
    fontSize: '48px',
    fontWeight: '300',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '58px',
  },
  logoMD: {
    fontSize: '38px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'uppercase',
    lineHeight: '46px',
  },
  logoXS: {
    fontSize: '18px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'uppercase',
    lineHeight: '22px',
  },
  navbarMD: {
    fontSize: '28px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '34px',
  },
  navbarXS: {
    fontSize: '18px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '22px',
  },
  sectionTitleMD: {
    fontSize: '60px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'uppercase',
    lineHeight: '72px',
  },
  sectionTitleXS: {
    fontSize: '36px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'uppercase',
    lineHeight: '43px',
  },
  cardTitleMD: {
    fontSize: '32px',
    fontWeight: '700',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '38px',
  },
  cardTitleXS: {
    fontSize: '24px',
    fontWeight: '700',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '29px',
  },
  destaqueMD: {
    fontSize: '38px',
    fontWeight: '300',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '46px',
  },
  destaqueXS: {
    fontSize: '24px',
    fontWeight: '300',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '29px',
  },
  cardText: {
    fontSize: '18px',
    fontWeight: '400',
    fontStyle: 'normal',
    textTransform: 'capitalize',
    lineHeight: '22px',
  },
  textInvokeModalMD: {
    fontSize: '36px',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: '43px',
  },
  textInvokeModalXS: {
    fontSize: '32px',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: '38px',
  },
};

export default typographyVariants;
